import { routeMap, routeNames } from '../../routes';

const baseUrl = 'https://rozmowni.pl';

const socialLinks = [
  'https://www.facebook.com/Rozmownipl-141305311401481',
  'https://www.instagram.com/rozmowni.pl/',
  'https://www.tiktok.com/@rozmowni.pl',
  'https://www.linkedin.com/in/ma%C5%82gorzata-rudowska-08a29a219',
];

// Social preview images, 1200×630, generated by scripts/generate-og-images.mjs.
const defaultImage = {
  url: `${baseUrl}/images/og-default.jpg`,
  height: 630,
  width: 1200,
  type: 'image/jpeg',
  alt: 'Rozmowni.pl – mów swobodnie po angielsku. Kursy angielskiego online',
};

const testImage = {
  url: `${baseUrl}/images/og-test.jpg`,
  height: 630,
  width: 1200,
  type: 'image/jpeg',
  alt: 'Bezpłatny test poziomujący z angielskiego online – Rozmowni.pl',
};

const logo = {
  '@type': 'ImageObject',
  height: 512,
  url: `${baseUrl}/logo512.png`,
  width: 512,
};

const fallback = {
  title:
    'Nauka języka przez Internet | Angielski online przez Google Meet, Zoom',
  description:
    'Praktyczne lekcje angielskiego z naciskiem na konwersacje w ciekawych tematach dotyczących rozwoju osobistego, psychologii, coachingu, relacji społecznych. Równoczesny rozwój kompetencji przyszłości: komunikacji, kreatywności, radzenie sobie z trudnymi emocjami, przełamywaniem bariery językowej.',
};

const postfix = ' | Rozmowni.pl';

function getOrganizationJsonLd(canonicalUrl) {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Witkowicka 68G/1',
      postalCode: '31-242',
      addressLocality: 'Kraków',
      addressRegion: 'małopolskie',
      addressCountry: 'PL',
    },
    name: 'Rozmowni.pl',
    description: 'Szkoła języka angielskiego online',
    logo,
    sameAs: socialLinks,
    url: canonicalUrl,
    contactPoint: [
      {
        '@type': 'ContactPoint',
        telephone: '+48506262227',
        contactType: 'customer service',
        areaServed: 'PL',
        availableLanguage: ['en', 'pl'],
      },
    ],
    brand: [
      {
        '@type': 'Brand',
        logo,
        url: canonicalUrl,
        name: 'Rozmowni.pl',
      },
    ],
    telephone: '+48506262227',
    email: 'kontakt@rozmowni.pl',
  };
}

function getWebPageJsonLd(canonicalUrl) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': canonicalUrl,
  };
}

function getBreadcrumbsJsonLd(name, canonicalUrl) {
  return {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Strona główna',
        item: `${baseUrl}`,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name,
        item: canonicalUrl,
      },
    ],
  };
}

function getHomeMetadata(canonicalUrl) {
  const title = `Angielski online: konwersacje, kursy 1:1 i grupowe${postfix}`;
  const description =
    'Sprawdź poziom angielskiego za darmo w 10 minut i odbierz bezpłatną lekcję próbną oraz e-book. Konwersacje na ciekawe tematy, kursy 1:1 i w małych grupach online.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getOrganizationJsonLd(canonicalUrl),
    ],
  };
}

function _getWhyUs(canonicalUrl) {
  const title =
    'Dlaczego my? | Czemu miałbyś uczyć się angielskiego w Rozmowni.pl';
  const description =
    'Nauka z Rozmowni.pl? Gwarancja ciekawych zajęć dotyczących rozwoju osobistego, psychologii, filozofii, coachingu. Równoczesny rozwój kompetencji przyszłości: komunikacji, kreatywności, radzenie sobie z trudnymi emocjami, przełamywaniem bariery językowej przez konwersacje online';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Dlaczego my?', canonicalUrl),
    ],
  };
}

function getAboutUs(canonicalUrl) {
  const title = 'O nas | Angielski online w szkole językowej Rozmowni.pl';
  const description =
    'Szkoła angielskiego online Rozmowni.pl: przyjazna atmosfera bez ocen i testów, konwersacje na tematy, które Cię interesują. Poznaj Gosię i zespół lektorów.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('O nas', canonicalUrl),
    ],
  };
}

function getPricing(canonicalUrl) {
  const title = `Cennik lekcji angielskiego online – 1:1, pary, grupy${postfix}`;
  // Prices mirror pages/cennik/index.js - change both together.
  const description =
    'Cennik lekcji angielskiego online: zajęcia indywidualne 120 zł za 45 min, lekcje w parach 65 zł od osoby, kursy w grupach 3–4 osób od 1430 zł za semestr.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Cennik', canonicalUrl),
    ],
  };
}

function getIndividualCourse(canonicalUrl) {
  const title = `Indywidualne lekcje angielskiego online (1:1)${postfix}`;
  const description =
    'Lekcje angielskiego online 1:1 przez Zoom lub Google Meet: konwersacje, General i Business English, egzaminy. 45 minut, tempo i tematy dopasowane do Ciebie.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Kursy indywidualne', canonicalUrl),
    ],
  };
}

function getGroupCourse(canonicalUrl) {
  const title = `Kursy grupowe angielskiego online – konwersacje, Business English${postfix}`;
  const description =
    'Kurs angielskiego online w małej grupie: konwersacje, General English, Business English. Poziomy A2–C2, zajęcia raz w tygodniu po 90 minut, 30 lekcji w semestrze.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Kursy grupowe', canonicalUrl),
    ],
  };
}

function getExam8Course(canonicalUrl) {
  const title = `Kurs angielskiego do egzaminu ósmoklasisty online${postfix}`;
  const description =
    'Roczny kurs angielskiego online przygotowujący do egzaminu ósmoklasisty: grupa 3–4 osób, zajęcia raz w tygodniu po 90 minut, 26 lekcji w semestrze.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Egzamin 8-klasisty', canonicalUrl),
    ],
  };
}

function getMaturaExamCourse(canonicalUrl) {
  const title = `Kurs do matury z angielskiego online${postfix}`;
  const description =
    'Kurs angielskiego online do matury na poziomie podstawowym i rozszerzonym: grupa 3–4 osób, zajęcia raz w tygodniu po 90 minut, 26 lekcji w semestrze.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Egzamin maturalny', canonicalUrl),
    ],
  };
}

function getHolidayCourse(canonicalUrl) {
  const title = `Intensywny wakacyjny kurs angielskiego online${postfix}`;
  const description =
    'Wakacyjny kurs angielskiego online w małej grupie: przede wszystkim mówienie – dyskusje, negocjacje, scenki – plus gramatyka i słownictwo. Lipiec, 3 razy w tygodniu po 90 minut.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Intensywne kursy wakacyjne', canonicalUrl),
    ],
  };
}

function getContact(canonicalUrl) {
  const title = 'Kontakt – szkoła angielskiego online Rozmowni.pl, Kraków';
  const description =
    'Skontaktuj się z Rozmowni.pl: tel. +48 506 262 227, kontakt@rozmowni.pl albo formularz. Odpowiadamy w ciągu 24 h. Szkoła z Krakowa, lekcje online dla całej Polski.';

  return {
    title,
    description,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Kontakt', canonicalUrl),
    ],
  };
}

function getTest(canonicalUrl) {
  const title = `Bezpłatny test poziomujący z angielskiego online${postfix}`;
  const description =
    'Sprawdź poziom angielskiego (A1–C2) w 10 minut: 25 pytań, wynik od razu. W pakiecie bezpłatna lekcja próbna online i e-book „Czas na angielski”.';

  return {
    title,
    description,
    image: testImage,
    robots: 'index, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Test poziomujący', canonicalUrl),
    ],
  };
}

function getPrivacyPolicy(canonicalUrl) {
  const title = `Polityka prywatności${postfix}`;
  const description =
    'Polityka prywatności szkoły językowej Rozmowni.pl: jakie dane zbieramy, w jakim celu i jakie prawa Ci przysługują.';

  return {
    title,
    description,
    robots: 'noindex, follow',
    jsonLd: [
      getWebPageJsonLd(canonicalUrl),
      getBreadcrumbsJsonLd('Polityka prywatności', canonicalUrl),
    ],
  };
}

export const getPropertiesMap = {
  [routeNames.HOME]: getHomeMetadata,
  [routeNames.ABOUT_US]: getAboutUs,
  [routeNames.PRICING]: getPricing,
  [routeNames.INDIVIDUAL_COURSE]: getIndividualCourse,
  [routeNames.GROUP_COURSE]: getGroupCourse,
  [routeNames.EXAM_8_COURSE]: getExam8Course,
  [routeNames.HOLIDAY_COURSE]: getHolidayCourse,
  [routeNames.MATURA_EXAM_COURSE]: getMaturaExamCourse,
  [routeNames.CONTACT]: getContact,
  [routeNames.TEST]: getTest,
  [routeNames.PRIVACY_POLICY]: getPrivacyPolicy,
};

export function getMetadata(routeName) {
  const properties = getPropertiesMap[routeName];
  if (!properties) {
    // Paths outside routeMap (the 404 page, /email-preview) still need a title
    // and must stay out of the index. The 404 page sets its own title on top.
    return {
      title: fallback.title,
      meta: [{ name: 'robots', content: 'noindex, follow' }],
    };
  }

  const canonicalUrl = baseUrl + routeMap[routeName];
  const {
    description: pageDescription,
    image = defaultImage,
    jsonLd,
    robots,
    title: pageTitle,
  } = properties(canonicalUrl);

  const title = pageTitle || fallback.title;
  const description = pageDescription || fallback.description;

  const metadata = {
    title,
    meta: [
      {
        name: 'description',
        content: description,
      },
      {
        name: 'author',
        content: 'Małgorzata Rudowska',
      },
      {
        property: 'og:site_name',
        content: 'Rozmowni.pl',
      },
      {
        property: 'og:title',
        content: title,
      },
      {
        property: 'og:description',
        content: description,
      },
      {
        property: 'og:type',
        content: 'website',
      },
      {
        property: 'og:url',
        content: canonicalUrl,
      },
      {
        property: 'og:image',
        content: image.url,
      },
      {
        property: 'og:image:secure_url',
        content: image.url,
      },
      {
        property: 'og:image:type',
        content: image.type,
      },
      {
        property: 'og:image:width',
        content: image.width,
      },
      {
        property: 'og:image:height',
        content: image.height,
      },
      {
        property: 'og:image:alt',
        content: image.alt,
      },
      {
        property: 'og:locale',
        content: 'pl_PL',
      },
      // X/Twitter reads its own tags from name=, not property=.
      {
        name: 'twitter:card',
        content: 'summary_large_image',
      },
      {
        name: 'twitter:title',
        content: title,
      },
      {
        name: 'twitter:description',
        content: description,
      },
      {
        name: 'twitter:image',
        content: image.url,
      },
      {
        name: 'twitter:image:alt',
        content: image.alt,
      },
    ],
    jsonLd,
  };

  if (robots) {
    metadata.meta.push({
      name: 'robots',
      content: robots,
    });
  }
  if (!robots?.match?.('noindex') && canonicalUrl) {
    metadata.canonicalUrl = canonicalUrl;
  }
  metadata.jsonLd = JSON.stringify(metadata.jsonLd);

  return metadata;
}
