name: "Deploy staging"
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    name: Deploy ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#      - run: npm ci --quiet
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Set release date as env variable
        run: echo "RELEASE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      - name: Set application directory as env variable
        run: echo "APP_DIR=/home/rozmowni/rails/test" >> $GITHUB_ENV
      - name: Create app archive
        run: tar --exclude=".git" --exclude=".github" -zcvf app_${{ env.RELEASE }}.tar.gz * .??*
      - name: Upload app archive to server
        run: rsync -av ./app_${{ env.RELEASE }}.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/rozmowni
      - name: Switch app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            mkdir -p ${{ env.APP_DIR }}/releases/${{ env.RELEASE }}
            mv ~/app_${{ env.RELEASE }}.tar.gz ${{ env.APP_DIR }}/releases/${{ env.RELEASE }}
            tar -xf ${{ env.APP_DIR }}/releases/${{ env.RELEASE }}/app_${{ env.RELEASE }}.tar.gz -C ${{ env.APP_DIR }}/releases/${{ env.RELEASE }}
            rm ${{ env.APP_DIR }}/releases/${{ env.RELEASE }}/app_${{ env.RELEASE }}.tar.gz
            rm ${{ env.APP_DIR }}/current
            ln -s ${{ env.APP_DIR }}/releases/${{ env.RELEASE }} ${{ env.APP_DIR }}/current
#            rm -rfv !($(ls ${{ env.APP_DIR }}/releases-r | head -2 | tr '\n' '|'))
            ls ${{ env.APP_DIR }}/releases -r | head -2 | tr '\n' '|'

